Re-apply some rules back
TailorBrands/tailor-rubocop pull request #14
Opened 2020-12-15 21:13 UTC by taltcher

# Background
Reapply the next rules:
- `Metrics/ParameterLists` - allow max of 3 non key parameters
- `Naming/MemoizedInstanceVariableName` - turn back on
- `Naming/MethodParameterName` - turn back on
- `Style/GlobalVars` - turn back on
- `Lint/CircularArgumentReference` - turn back on

## Did you make sure to?
### Project Management
- [ ] Review it as needed with the technical team leader?
- [ ] Attach the PR to the Trello card?

### PR
- [ ] Assign yourself to the PR
- [ ] Add at least one reviewer

### Before-Merge
- [ ] Update the repos dependent on those rules - delete the current cached rubocop.yml, and run `rubocop` again to refresh
- [ ] Validate changes against affected repositories, and if needed, prepare PRs to update repositories according to changes

### Post-Merge
- [ ] Verify that your Trello card was moved to today's release and that it was announced in #releases slack channel

2020-12-15 21:14 UTC, taltcher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rubocop rules debt - rules to re-apply and fix](https://trello.com/c/VJVl8WJO/368-rubocop-rules-debt-rules-to-re-apply-and-fix)

2020-12-15 21:58 UTC, selfish requested changes
Looking good. One change for consideration

2020-12-15 21:58 UTC, selfish commented on rubocop.yml
> +  Max: 3
I feel like 3 is waaaay to short.
How about 5 to start with? We have many functions with more than 3 i believe

2020-12-16 12:22 UTC, selfish approved these changes

2020-12-16 12:24 UTC, merged